apiVersion: v1
kind: Service
metadata:
  name: delivery-db-svc
  labels:
    app: delivery-db
spec:
  selector:
    app: delivery-db
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
    nodePort: 32100
  type: NodePort
