apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: delivery-db
spec:
  serviceName: delivery-db
  replicas: 1
  selector:
    matchLabels:
      app: delivery-db
  template:
    metadata:
      labels:
        app: delivery-db
    spec:
      containers:
      - name: delivery-db
        image: postgres:16.1
        envFrom:
        - configMapRef:
            name: delivery-db-config
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
