apiVersion: v1
kind: Service
metadata:
  name: delivery-api-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31500
  selector:
    app: delivery-api
  type: LoadBalancer
