name: 🔍 Code check
run-name: Code Check | @${{ github.actor }} | ${{ github.ref_name }}

on: [pull_request]

jobs:
#   vulncheck:
#     name: Analyzing vulnerability code ${{ github.ref_name }}
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Set up Go
#         uses: actions/setup-go@v4
#         with:
#             go-version: 1.19

#       - name: Install vulncheck
#         run: go install golang.org/x/vuln/cmd/govulncheck@latest

#       - name: Scan for Vulnerabilities in Code
#         run: govulncheck ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
            go-version: 1.20.6

      - name: Install Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@v0.4.3
    
      - name: Install Go Dependencies
        run: go mod download

      - name: Run quality checks
        run: |
            go vet ./...
    
      - name: Run Staticcheck
        run: staticcheck ./...